### PR TITLE
Add String slice method and tests

### PR DESCRIPTION
**Pull request by pawurb**
Hello. I am a Ruby developer playing around with Swift for a while now. One of the things I keep missing is **String#slice** method from Ruby stdlib. This is implementation that replicates the behaviour of a Ruby **String#slice** for integer argument types https://ruby-doc.org/core-2.2.0/String.html#method-i-slice . Kind of bombarded it with tests but wanted to cover all the edge cases. Hope that can be useful.

## Checklist

- [x] I checked the [**Contributing Guidelines**](https://github.com/omaralbeik/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [x] I have **only one commit** in this pull request.
- [x] New extensions support iOS 8 or later.
- [x] New extensions are written in Swift 3.
- [x] New extensions were created in **development branch**.
- [ ] Pull request was created to **development head branch**.
- [x] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [x] All comments headers have the word **SwifterSwift:** before description.

### CODE REVIEW

**Comment by muescha** [comment]
with the `slice(at: int)` i get this result:

```swift
let str1 = "The morning is upon us."
print(str1.slice(at: 12))  // -> Optional("i")
```

this makes sense because the `slice` is also notated in brackets `[]` in ruby:

 ```ruby
"abcd"[3] #-> 'd'
```

but somehow in swift i expect the `slice` more like the javascript slice (see [Javascript MDN | String.prototype.slice](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/String/slice) ):

```swift
let str1 = "The morning is upon us."
print(str1.slice(at: 12))  // -> Optional("is upon us.")
```

**Comment by pawurb** [comment]
If I change behaviour of only one argument function call, then it will not be compatible with neither JS nor Ruby implementation. Do you suggest going all for JS version then? Obviously I am biased but I prefer the Ruby one.

**Comment by muescha** [comment]
1) the 1 argument call can also done with the `"abced"[3]` call from SwifterSwift
2) i think the 2 argument call is now already JS compatible 

@omaralbeik what is your favorite?

**Comment by omaralbeik** [comment]
I was trying to avoid adding slice method, because it is implemented differently in different programming languages, however I think there is no escape from it :)

I refactored @pawurb code to the following
```swift
public func slice(from index: Int, length: Int) -> String? {
	guard length >= 0, index >= 0, index < characters.count,
		index.advanced(by: length) < characters.count  else {
		return nil
	}
	guard length > 0 else {
		return ""
	}
	let start = self.index(startIndex, offsetBy: index)
	let end = self.index(startIndex, offsetBy: index + length)
	return self[start...end]
}

public func slice(from startIndex: Int, to endIndex: Int) -> String? {
	return slice(from: startIndex, length: endIndex - startIndex)
}

public func slice(at index: Int) -> String? {
	return slice(from: index, to: characters.count - 1)
}
```

Example:
```swift
let s = "Hello world"
s.slice(from: 6, length: 4) // -> "world"
s.slice(from: 3, to: 10) // -> "lo world"
s.slice(at: 6) // -> "world"
```


@pawurb @muescha Your feedback is important,  what do you think of the above code, does it make sense to you?

**Comment by pawurb** [comment]
By calling the function parameter `index` you are shadowing internal String method `index`. Looks a bit confusing, even if you use `self.index` to call it later on. The same goes for `startIndex` and `endIndex` that are also native String methods.

Also: `s.slice(from: 6, length: 4)` returns the string that is 5 characters long. It is not compatible with neither Ruby nor JS implementation. I think you should change:

`let end = self.index(startIndex, offsetBy: index + length)` to
`let end = self.index(startIndex, offsetBy: index + length - 1)`

Apart from it looks ok.

**Comment by muescha** [comment]
thx for the hint about shadowing 

to avoid confusion we can rename the parameter to `sliceStartIndex` and `sliceEndIndex`

```
return slice(from: startIndex, length: endIndex - startIndex)
```



this can be done by:
```
return self[sliceStartIndex... sliceEndIndex]
```


and 
```
return slice(from: index, to: characters.count - 1)
```

can use the internal endIndex:
```
return self[sliceIndex...endIndex]
````

**Comment by omaralbeik** [comment]
@pawurb @muescha How about now

```swift
public func slice(from i: Int, length: Int) -> String? {
	guard length >= 0, i >= 0, i < characters.count,
		i.advanced(by: length) <= characters.count  else {
		return nil
	}
	guard length > 0 else {
		return ""
	}
	return self[i..<i.advanced(by: length)]
}

public func slice(from start: Int, to end: Int) -> String? {
	return self[start..<end]
}

public func slice(at i: Int) -> String? {
	guard i < characters.count else {
		return nil
	}
	return self[i..<characters.count]
}
```

Example
```swift
let s = "Hello world"
s.slice(from: 6, length: 5) // -> "world"
s.slice(from: 6, to: 11) // -> "world"
s.slice(at: 6) // -> "world"
```

**Comment by pawurb** [comment]
👍 as long as the specs are green ;)

**Comment by muescha** [comment]
1) i think you can safe use `endIndex` instead of `characters.count` because its an native method and maybe faster 
2) i would expect in the case of `i.advanced(by: length) <= characters.count` then it should be all until the end:
> If intEnd < 0, let to be max(len + intEnd,0); otherwise let to be min(intEnd, len)

https://tc39.github.io/ecma262/#sec-string.prototype.slice

**Comment by muescha** [comment]
@pawurb reading the specs i see what you mean with the difference to ruby and JS. in javascript it is `slice(start[,end]) `

**Comment by omaralbeik** [comment]
@muescha 
1. endIndex is not of type Int it is of type (String.Index), I was not even able to cast it to Int
2. correct, how about this this:

```swift
public func slice(from i: Int, length: Int) -> String? {
	guard length >= 0, i >= 0, i < characters.count  else {
		return nil
	}
	guard i.advanced(by: length) <= characters.count else {
		return slice(at: i)
	}
	guard length > 0 else {
		return ""
	}
	return self[i..<i.advanced(by: length)]
}
```

**Comment by muescha** [comment]
thats ok

the edge cases should also go into the unit tests :)

**Comment by omaralbeik** [comment]
@pawurb Please re-create this request from development head branch to merge it.

**Pull request merged**
