### PR TITLE
safe way to access array index elements no worry of out of bounds

### PR DESCRIPTION
**Pull request by sairamkotha**
## Checklist

- [x] I checked the [**Contributing Guidelines**](https://github.com/omaralbeik/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [x] I have **only one commit** in this pull request.
- [x] New extensions support iOS 8 or later.
- [x] New extensions are written in Swift 3.
- [x] New extensions were created in **development branch**.
- [x] Pull request was created to **development head branch**.
- [x] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [x] All comments headers have the word **SwifterSwift:** before description.

### CODE REVIEW

**Comment by sairamkotha** [comment]
Sure Will make changes.

**Comment by sairamkotha** [comment]
Pushed my changes to CollectionExtensions.Swift.
Thanks

**Comment by omaralbeik** [comment]
@sairamkotha Merged into development branch, will be added to master in the next release. Thank you!

**Comment by sairamkotha** [comment]
@omaralbeik Thanks for merging.

**Comment by omaralbeik** [comment]
Added to [v1.4.2](https://github.com/omaralbeik/SwifterSwift/wiki/whats-new#v142)
Thank you @sairamkotha!

**Pull request merged**
